### ISSUE TITLE
Azure storage doesn't work in Ubuntu 14.04.2

### ISSUE THREAD

**Issue by Uburwator** [wal-e/wal-e#201]
I was able to make backups to S3, but not to Azure, got an error:
>DETAIL: The subcommand is "backup-push".
>STRUCTURED: time=2015-09-21T20:44:52.163131-00 pid=50907
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
>        DETAIL: Traceback (most recent call last):
>         File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 534, in main
>            backup_cxt = configure_backup_cxt(args)
>          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 466, in configure_backup_cxt
>            from wal_e.blobstore import wabs
>          File "/usr/local/lib/python2.7/dist-packages/wal_e/blobstore/wabs/__ init __.py", line 2, in <module>
>            from wal_e.blobstore.wabs.wabs_util import do_lzop_get
>          File "/usr/local/lib/python2.7/dist-packages/wal_e/blobstore/wabs/wabs_util.py", line 10, in <module>
>            from azure import WindowsAzureMissingResourceError
>        **ImportError: cannot import name WindowsAzureMissingResourceError**

It looks like tho code written isn't compatible with modern Azure SDK.
### Fix which helped:
replaced
```
from azure import WindowsAzureMissingResourceError
from azure.storage import BlobService
```

to

`from azure.storage.blob import BlobService`

in lines 10-11 of /usr/local/lib/python2.7/dist-packages/wal_e/blobstore/wabs/wabs_util.py
and the first line in /usr/local/lib/python2.7/dist-packages/wal_e/blobstore/wabs/calling_format.py:

From 
`from azure.storage.blobservice import BlobService`
to 
`from azure.storage.blob import BlobService` - this fixed another error ("ImportError: No module amed blobservice"). 

### pip freeze:
```
Babel==2.0
Landscape-Client==14.12
PAM==0.4.2
Twisted-Core==13.2.0
apt-xapian-index==0.45
argparse==1.2.1
azure==1.0.1
azure-common==1.0.0
azure-mgmt==0.20.0
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.20.0
azure-mgmt-network==0.20.0
azure-mgmt-nspkg==1.0.0
azure-mgmt-resource==0.20.0
azure-mgmt-storage==0.20.0
azure-nspkg==1.0.0
azure-servicebus==0.20.1
azure-servicemanagement-legacy==0.20.1
azure-storage==0.20.1
boto==2.38.0
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
debtcollector==0.8.0
futures==3.0.3
gevent==1.0.2
greenlet==0.4.9
html5lib==0.999
iso8601==0.1.10
monotonic==0.3
msgpack-python==0.4.6
netaddr==0.7.18
netifaces==0.10.4
oslo.config==2.4.0
oslo.i18n==2.6.0
oslo.serialization==1.9.0
oslo.utils==2.5.0
pbr==1.8.0
prettytable==0.7.2
pyOpenSSL==0.13
pyserial==2.6
python-apt==0.9.3.5ubuntu1
python-dateutil==2.4.2
python-debian==0.1.21-nmu2ubuntu2
python-keystoneclient==1.7.1
python-swiftclient==2.6.0
pytz==2015.6
requests==2.7.0
six==1.9.0
ssh-import-id==3.21
stevedore==1.8.0
urllib3==1.7.1
wal-e==0.8.1
wheel==0.24.0
wrapt==1.10.5
wsgiref==0.1.2
zope.interface==4.0.5
```

**Comment by fdr** [comment]
I actually have a patch for this but have been holding off on deploying it because of testing. Can I give you a patch and you would be so kind as to make sure it doesn't bust everything up?

**Comment by Uburwator** [comment]
Yes, it would be great. Actually I mentioned all needed changes in issue, but it will be interesting to compare it with your patch.

**Comment by fdr** [comment]
Try this out: https://github.com/wal-e/wal-e/tree/v0.9

I'm going to bulk-process a lot of the WAL-E backlog, so I decided to start v0.9 devel just now...but this should be stable, because it's v0.8 + just Azure fix right now.

**Comment by pdeva** [comment]
could you port this fix to 0.8 tree and release since it doesnt look like 0.9 will be out anytime soon

**Comment by fdr** [comment]
Yeah, let me have a look at that. Either that, or just release v0.9. I'll have a look...

**Comment by fdr** [comment]
I opted to release v0.9 instead.
