### ISSUE TITLE
wal-push fails with AttributeError: type object 'Connection' has no attribute 'SCOPE' with google cloud storage

### ISSUE THREAD

**Issue by kapilratnani** [wal-e/wal-e#346]
Hi,
I am trying to setup wal-e with google cloud storage. Cannot figure out why this fails.
Please help.

**Comment by kapilratnani** [comment]
It seems there has been some changes in the google storage API.
in blobstore/gs/calling_format.py
I changed "Connection.SCOPE" to 'Client.SCOPE' and changed connect method a bit, atleast wal-push is working now. 
Will check other methods and update

**Comment by deverant** [comment]
Hey!

What version of the google-cloud-storage package are you using? The code worked with 0.22.0 so I am interested in knowing how much newer version you are using that the API for that library changed.

**Comment by kapilratnani** [comment]
I used the latest version 1.1.1

**Comment by deverant** [comment]
Hey, a commit was merged yesterday that uses a newer google cloud storage library. Can you verify if it fixes the issues you have seen?
