### ISSUE TITLE
wal-e backup-push does't work with Python 3.6

### ISSUE THREAD

**Issue by yteraoka** [wal-e/wal-e#322]
```
-bash-4.2$ /opt/wal-e/bin/wal-e --aws-instance-profile --s3-prefix s3://****/wal-e backup-push $PGDATA
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2017-03-07T15:00:32.823141-00 pid=14150
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to s3://****/wal-e/basebackups_005/base_0000000100000002000000FE_00000040/extended_version.txt.
        STRUCTURED: time=2017-03-07T15:00:35.386069-00 pid=14150
wal_e.operator.backup INFO     MSG: postgres version metadata upload complete
        STRUCTURED: time=2017-03-07T15:00:35.458788-00 pid=14150
wal_e.worker.upload INFO     MSG: beginning volume compression
        DETAIL: Building volume 0.
        STRUCTURED: time=2017-03-07T15:00:35.585929-00 pid=14150
Traceback (most recent call last):
  File "/opt/wal-e/lib64/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/wal-e/lib64/python3.6/site-packages/wal_e/worker/upload.py", line 97, in __call__
    tpart.tarfile_write(pl.stdin)
  File "/opt/wal-e/lib64/python3.6/site-packages/wal_e/tar_partition.py", line 315, in tarfile_write
    self._padded_tar_add(tar, et_info)
  File "/opt/wal-e/lib64/python3.6/site-packages/wal_e/tar_partition.py", line 242, in _padded_tar_add
    tar.addfile(et_info.tarinfo, f)
  File "/usr/lib64/python3.6/tarfile.py", line 1973, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
TypeError: copyfileobj() got an unexpected keyword argument 'bufsize'
Wed Mar  8 00:00:35 2017 <Greenlet at 0x7f6121e8e5a0: <wal_e.worker.upload.PartitionUploader object at 0x7f6121e9f940>([ExtendedTarInfo(submitted_path='/var/lib/pgsql/9.)> failed with TypeError

wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2017-03-07T15:00:35.701163-00 pid=14150
NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/opt/wal-e/lib64/python3.6/site-packages/wal_e/cmd.py", line 627, in main
            pool_size=args.pool_size)
          File "/opt/wal-e/lib64/python3.6/site-packages/wal_e/operator/backup.py", line 197, in database_backup
            **kwargs)
          File "/opt/wal-e/lib64/python3.6/site-packages/wal_e/operator/backup.py", line 504, in _upload_pg_cluster_dir
            pool.join()
          File "/opt/wal-e/lib64/python3.6/site-packages/wal_e/worker/upload_pool.py", line 120, in join
            self._wait()
          File "/opt/wal-e/lib64/python3.6/site-packages/wal_e/worker/upload_pool.py", line 65, in _wait
            raise val
          File "/opt/wal-e/lib64/python3.6/site-packages/gevent/greenlet.py", line 536, in run
            result = self._run(*self.args, **self.kwargs)
          File "/opt/wal-e/lib64/python3.6/site-packages/wal_e/worker/upload.py", line 97, in __call__
            tpart.tarfile_write(pl.stdin)
          File "/opt/wal-e/lib64/python3.6/site-packages/wal_e/tar_partition.py", line 315, in tarfile_write
            self._padded_tar_add(tar, et_info)
          File "/opt/wal-e/lib64/python3.6/site-packages/wal_e/tar_partition.py", line 242, in _padded_tar_add
            tar.addfile(et_info.tarinfo, f)
          File "/usr/lib64/python3.6/tarfile.py", line 1973, in addfile
            copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
        TypeError: copyfileobj() got an unexpected keyword argument 'bufsize'

        STRUCTURED: time=2017-03-07T15:00:37.771104-00 pid=14150
-bash-4.2$
```
It seems to be due to change of tarfile.py.
https://github.com/python/cpython/blob/3.5/Lib/tarfile.py
https://github.com/python/cpython/blob/3.6/Lib/tarfile.py

bufsize is always None?

```
$ uname -a
Linux ip-172-31-28-236.ap-northeast-1.compute.internal 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Python 3.6 installed from IUC repository.

```
$ yum list installed | grep python36
python36u.x86_64                           3.6.0-2.ius.centos7         @ius
python36u-libs.x86_64                      3.6.0-2.ius.centos7         @ius
python36u-pip.noarch                       9.0.1-1.ius.centos7         @ius
python36u-setuptools.noarch                32.3.1-1.ius.centos7        @ius
```

**Comment by fdr** [comment]
Thanks for the bug report.

Looks like Python 3.6 added a good feature, and that broke my workaround: instead of having to do my weird monkeypatch thing in `copyfileobj.py`, we might be able set the bufsize on a tarfile object directly (`copybufsize`).

How would you feel about patching this so that WAL-E's `copyfileobj` is not used on Python >= 3.6?

**Comment by yteraoka** [comment]
Thanks.
That proposal sounds good to me.
I tried deleting the patch.
It worked.

**Comment by brikou** [comment]
Hello!
As written in readme, v1.1.0 is tested against python v3.6... sadly it still doesn't work with python 3.6, do you have any ETA for this fix?
Thanks a lot

**Comment by yteraoka** [comment]
@brikou 
Hi,
I tried that a half year ago. I did just simple test, and I have completely forgot that.
Before I tried that, the system began with python 3.5 now.
I will try again, so Please give me some time.

**Comment by yteraoka** [comment]
@brikou
I tried again.

Following patch worked with Python 3.6 and 3.5. Could you please verify that this patch works?

```diff
--- /tmp/cmd.py.orig    2017-01-03 21:00:11.000000000 +0000
+++ /opt/wal-e/lib/python3.6/site-packages/wal_e/cmd.py 2017-09-08 10:31:53.567664129 +0000
@@ -589,7 +589,8 @@
         backup_cxt = configure_backup_cxt(args)

         if subcommand == 'backup-fetch':
-            monkeypatch_tarfile_copyfileobj()
+            if not (sys.version_info.major >= 3 and sys.version_info.minor >= 6):
+                monkeypatch_tarfile_copyfileobj()

             external_program_check([LZOP_BIN])
             backup_cxt.database_fetch(
@@ -601,7 +602,8 @@
         elif subcommand == 'backup-list':
             backup_cxt.backup_list(query=args.QUERY, detail=args.detail)
         elif subcommand == 'backup-push':
-            monkeypatch_tarfile_copyfileobj()
+            if not (sys.version_info.major >= 3 and sys.version_info.minor >= 6):
+                monkeypatch_tarfile_copyfileobj()

             if args.while_offline:
                 # we need to query pg_config first for the
```

**Comment by vmihailenco** [comment]
Ping. wal-e is still broken with Python 3.6.

**Comment by yteraoka** [comment]
hmm.. :confused: 
My tested environment below.
```
$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)

$ yum list installed | grep postgresql
postgresql96.x86_64                         9.6.5-1PGDG.rhel7          @pgdg96  
postgresql96-libs.x86_64                    9.6.5-1PGDG.rhel7          @pgdg96  
postgresql96-server.x86_64                  9.6.5-1PGDG.rhel7          @pgdg96

$ yum list installed | grep python36
python36u.x86_64                            3.6.2-1.ius.centos7        @ius     
python36u-libs.x86_64                       3.6.2-1.ius.centos7        @ius     
python36u-pip.noarch                        9.0.1-1.ius.centos7        @ius     
python36u-setuptools.noarch                 33.1.1-1.ius.centos7       @ius
```

Installing WAL-E (S3 storage only)

```
# python3.6 -m venv /opt/wal-e
# /opt/wal-e/bin/pip install wal-e[aws]==1.1.0b1
# /opt/wal-e/bin/wal-e version
1.1.0b1
```
then apply the patch that disable `monkeypatch_tarfile_copyfileobj()` to `cmd.py`.

Which version do you use?
What error message displayed?

**Comment by vmihailenco** [comment]
@yteraoka I only mean that master branch is still broken. Your patch is probably working, but it would be nice if we get it into master branch...

**Comment by h4k1m0u** [comment]
I got the same error as well when I updated to `Python3.6` on `FreeBSD11`.
The version of `Wal-e` installed is `1.1.0`.

**Comment by technion** [comment]
I can confirm that with 1.1.0 and your patch applied, the issue is resolved for me. It would be great to see this committed.

**Comment by loganb** [comment]
Hello all, 

I'm getting this same failure using Python 3.6.4 and Wal-e 1.1.0b1 on OS X. I'm having trouble following the thread here. Is there a working workaround? Thanks!

**Comment by h4k1m0u** [comment]
@loganb There's a patch (proposed by @yteraoka) but I'm not sure how to apply it.

**Comment by sofuca** [comment]
Can confirm that this the above patch is working with the latest version of wal-e.

**Comment by fdr** [comment]
@deverant any objections to merging this one? Patch seems fine to me on inspection.

**Comment by deverant** [comment]
@fdr Looks good to me 👍

**Comment by thorsten-plause** [comment]
@fdr or @technion Any chance one of you can prepare a release with the python 3.6 support? Thank you!

**Comment by technion** [comment]
@thorsten-plause  I am not a committer here.

**Comment by nimda7** [comment]
@thorsten-plause install it from master branch directly
``pip install git+https://github.com/wal-e/wal-e.git
``

**Comment by thorsten-plause** [comment]
@nimda7 I am deploying it in a docker container, so using git is much harder. However, I just checked it out locally and copied the repo  into my docker container for installation and that seems to work. 
But still might be good to cut a release, the last release was done >6 months back.

**Comment by duanhongyi** [comment]
Can you publish an updated version? Even if it's just to solve this bug.

**Comment by progvp** [comment]
Why is this bug marked as Closed? This bug still exists with Python 3.6 and wal-e 1.1.0

**Comment by candysmurf** [comment]
@yteraoka, I ran into the same error. I need to make wale work inside a Docker container. Any help is greatly appreciated.

**Comment by yteraoka** [comment]
@candysmurf I think this issue is resolved in #384 with a better way. But, It's not yet released on PyPI. You can install from github like this: `pip install git+https://github.com/wal-e/wal-e.git@master`. Be careful other changes in master branch. https://github.com/wal-e/wal-e/compare/v1.1.0...master

**Comment by candysmurf** [comment]
@yteraoka, thanks for your quick help. I'll give it a try.

**Comment by candysmurf** [comment]
@yteraoka, yes, it worked for me. Thanks for your help! Do you know when this fix will be released?

**Comment by yteraoka** [comment]
@candysmurf Sorry, I'm not a maintainer. Please ask in Google Groups. https://groups.google.com/forum/#!forum/wal-e

Or maybe you can use WAL-G instead of WAL-E.
https://github.com/wal-g/wal-g

**Comment by candysmurf** [comment]
@yteraoka, Thanks for all of your help! It gets us going for now. I'll look into WAL-G soon.

**Comment by fdr** [comment]
I suppose I should make a release. But WAL-G, though a bit rough, seems
useful to people.

**Comment by relgames** [comment]
Hi, it still fails:
```
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python3.6/dist-packages/wal_e/cmd.py", line 652, in main
            pool_size=args.pool_size)
          File "/usr/local/lib/python3.6/dist-packages/wal_e/operator/backup.py", line 197, in database_backup
            **kwargs)
          File "/usr/local/lib/python3.6/dist-packages/wal_e/operator/backup.py", line 504, in _upload_pg_cluster_dir
            pool.join()
          File "/usr/local/lib/python3.6/dist-packages/wal_e/worker/upload_pool.py", line 120, in join
            self._wait()
          File "/usr/local/lib/python3.6/dist-packages/wal_e/worker/upload_pool.py", line 65, in _wait
            raise val
          File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
          File "/usr/local/lib/python3.6/dist-packages/wal_e/worker/upload.py", line 97, in __call__
            tpart.tarfile_write(pl.stdin)
          File "/usr/local/lib/python3.6/dist-packages/wal_e/tar_partition.py", line 324, in tarfile_write
            self._padded_tar_add(tar, et_info)
          File "/usr/local/lib/python3.6/dist-packages/wal_e/tar_partition.py", line 243, in _padded_tar_add
            tar.addfile(et_info.tarinfo, f)
          File "/usr/lib/python3.6/tarfile.py", line 1980, in addfile
            copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
        TypeError: copyfileobj() got an unexpected keyword argument 'bufsize'
```

Installed with `pip install git+https://github.com/wal-e/wal-e.git@master`
Python 3.6.9

**Comment by relgames** [comment]
Can you reopen this bug as obviously is't still not fixed, even in master branch?

**Comment by relgames** [comment]
Hi, installing from master branch fixed it. Is there a release planned? Or is it recommended to just switch to WAL-G?

**Comment by thedevelopnik** [comment]
WAL-G still doesn't support tablespaces (a recent release had a "preview" for which there is no documentation"), so it's not an effective switch for those of us using tablespaces.

**Comment by fdr** [comment]
FYI, I rather quietly released a version of WAL-E with the tip of master
that supports later pythons.
