### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'size'

### ISSUE THREAD

**Issue by boncey** [wal-e/wal-e#216]
I'm seeing the following error when doing a backup-push to S3.

```
$ /usr/bin/envdir $HOME/.etc/wal-e.d/env /usr/local/bin/wal-e --terse backup-push $HOME/conf/db/postgres/data

wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2015-12-22T12:54:51.298808-00 pid=21009
NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 572, in main
            pool_size=args.pool_size)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 197, in database_backup
            **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 497, in _upload_pg_cluster_dir
            for tpart in parts:
          File "/usr/local/lib/python2.7/dist-packages/wal_e/tar_partition.py", line 393, in _segmentation_guts
            if et_info.tarinfo.size > max_partition_size:
        AttributeError: 'NoneType' object has no attribute 'size'

        STRUCTURED: time=2015-12-22T12:54:56.506926-00 pid=21009
```

This is on a newly installed PostgreSQL 9.3 on Ubuntu 14.04.3.
My settings:
```
wal_level = archive
archive_mode = on
archive_command = 'envdir /home/boncey/.etc/wal-e.d/env wal-e --terse wal-push %p'
archive_timeout = 60
```

I had this working on PostgreSQL 8.1 on the same machine with no problems. Now I've switched to 9.3 and it's stopped working.
```
% cat /etc/issue.net
Ubuntu 14.04.3 LTS
% python --version
Python 2.7.6
% wal-e version
0.8.1
% psql --version
psql (PostgreSQL) 9.3.10
```

I've dropped and recreated the S3 bucket in case the 8.1 backups were confusing it somehow but it has made no difference.

**Comment by boncey** [comment]
I upgraded to `0.9.0` (on the off chance) but it has made no difference.

Is anyone else having this same problem?

I added in some debugging to the library to print out the `et_info` class when it's defined.
Most lines look like this...

    ExtendedTarInfo(submitted_path='/*******************/postgres/data/.tmp/.s.PGSQL.5432.lock', tarinfo=<TarInfo '.tmp/.s.PGSQL.5432.lock' at 0x7f838b30c350>)

This is what I saw right before it failed....

    ExtendedTarInfo(submitted_path='/*******************/postgres/data/.tmp/.s.PGSQL.5432', tarinfo=None)

I don't know why that happens or what it means. But hopefully this will help someone with more knowledge of `wal-e`.

**Comment by boncey** [comment]
I have figured it out! :-)

The file mentioned above is the postrgres networking socket (set in `unix_socket_directories`).
I guess `wal-e` can't read it properly as it's not a regular file.

The solution is to move that tmp dir outside of the `data` directory so that `wal-e` no longer tries to read it.
